---
- name: Create Static Website
  hosts: all
  become: true

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Install Unzip
      yum:
        name: unzip
        state: present

    - name: Download frica.zip
      get_url:
        url: "https://www.free-css.com/assets/files/free-css-templates/download/page288/frica.zip"
        dest: "/var/www/html/frica.zip"

    - name: Unzip frica.zip
      command: unzip -o /var/www/html/frica.zip -d /var/www/html/
